language: node_js
node_js:
- '0.12'
- '4.0'
- stable
script: "npm run test:node && npm run test:saucelabs"
addons:
  sauce_connect: true
env:
  global:
    - secure: ouzHsXjQqFa1Y/UngHMZiRO8slesSgeG61rMF5ZaYmZul7BemdzXJps05sQqx7Jukpl3CpsGK+E2zgcIPeho1REnSbfIrZwMYvzr2BbBBMR/J1SJ+M+tte3xWKVBOXsjmjZi1HZ9hEQpVWeS9czmizTTqNNTfAx8+rF+tUqmeAbC9gk/rdDW5bjGPmQpivHU5cOlcRta36z9qZNG6xrQeyIl00OCINCf68oOYLz0NewvOnsykKfnAVlb+ddDE8k7iKO9UFApjFHfgBNDD9gZVSLeQlD9LA62YiZ1SPbRfe8pcO8K7uqSgg+KTDNDURbi2ITkBQxhh7zhl4QdBW5l6ec9au6qpOo1PYLF+Y+km4a/6SjdIZkLktuoPqb/9aZonR2Mqq6K8F5q6iaGwa1Jh8W+Rv0NNF4Q4SJhcE4zgI+V2A+pmtPHoRMqFm5PqEEdBQiQpquh+qFbSo/pBB8ZkfOXVIYAIIWMyGI0kQHCUpZnWbyaVuP+jUyTnOPNnIrtuDz/HT72De4e2jj8Q5qiq1MB4ZVmL2Ka7MGkCZCWPGN88SlyzJfjRjcBeIRKvkUWfU65EkavFoKULW58TC+mztcxrkUyye4XcevVDtEjFuOwqAusqFy5vSik9TmGZHW8y9Gq0PLrZiKJ6InKShDw0fBxQN4ZSVYF8u3Fge+5/iU=
    - secure: IEr8aF3Hp3PYmZbHi7KSKlmMJr/5tA48yAriFuDHe4MDAf9rEllSeskcyOhxRjt46vgHv/6qRlO+wmB5WqpVB9afhjzxo4ZVoA9MLhX2QBzXasEHrZUed7exNBByZVgMlE1sbe0nR8zklAz3N50qXWYNivFF6eYPTayfXB53tGSwbuRwXRVXB1oGb6DVElwzUuTFlDkTP/wOMOtKRhPr13/IOBYGMJL6RnV//gj7vXjQmYlBFyyu1ta7CgnGsLHFsPGwx4NhnGfSYf06SLx+glPcTHec6tzjqWBQyWdR/TjWCV99ohGNaeISKlLnwc5iUthqhoa/K34FsSMB95Rz8rNWvyU3fATg+4/wc5LRMaM+Rrkee6ttwg1bh51FxkI3CrCDVQRsR3K48txrMpSVwoVQiApjRhbpFREqtYzDaR2LanntOqzoMI84pPu4Xk9rqo49gNfCE4Z14GVn6xMwgcLvawGGAOS/YxfIkNkq4W9dy6aFED7UWFdflh3BqF86rVBUQ5V7tQzMLoGR9YvW0VEPNvGz8emtyGYxsYWKU/sLahk9HfV385dpOlK/0rEg+yeMnlyEGvtTXR8B+RGOpjuvB8REFMMJ3vsV4qyCePRfzgN0ngCntzPVh/Ztj+eGN1W+Wrhy2cH2he0umJC1I0utovfazxEjR8xD0TK1gbw=

